# Setup
title:               Eder M.
tagline:             'w.i.p'
description:         'Feel free to poke around.'
url:                 https://medinaeder.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Eder Medina
  url:               
  email:             e_medina at g dot harvard dot edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
